# Generated by Django 4.2.1 on 2023-06-14 14:36

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='data',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='agency',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='b2bB2c',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='billNumber',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='billingAddress',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='birthDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cardAuthorizationCode',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cardNsu',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='checkingAccount',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='codeBank',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='codigoExternoFrete',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cpf_cnpj',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='creditCardFlag',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='crossDocking',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='customerExternalId',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='dateOrder',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='deliveryShipping',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='deliveryTime',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='descricaoDetalhada',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='expirationDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='externalId',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='gender',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='group',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='historyListOrderStatus',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='idAdminCard',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='idCustomer',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='idOrder',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='idPaymentBrand',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='idPaymentType',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='idQueue',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='idSeller',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='idShipping',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='idShippingHub',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='idTypePayment',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='interestValue',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='marketPlaceDateCreated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='marketPlaceID',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='marketPlaceName',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='marketPlaceNumberOrder',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='marketPlaceStore',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='metaData',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='nameBank',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='nameCarrying',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='nameCustomer',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='namePaymentMethodGateway',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='nameShipping',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='nameStatus',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='numberOfInstallments',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='orderCD',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='orderItems',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='orderNotes',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='orderPayment',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='orderType',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='orderZapcommerce',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='originApp',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='paymentDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='paymentFormDescription',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='paymentFormId',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='paymentLink',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='phone1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='phone2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='proofOfSale',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='recurrentCodePlan',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='recurrentSelectedTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='rg_ie',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='sellerCode',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shippingCompany',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shippingMode',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shippingRegister',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='totalDiscount',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='totalInstallment',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='totalItens',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='totalShipping',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='totalShoppingVoucher',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='trackingLink',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='typeCustomer',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='usefulDay',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='valueOfInstallment',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
    ]
