# Generated by Django 4.2.1 on 2023-06-26 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
        ('orders', '0002_order_customer_orderproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='order',
        ),
        migrations.RemoveField(
            model_name='product',
            name='artes',
        ),
        migrations.RemoveField(
            model_name='product',
            name='idOrderItem',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='artes',
            field=models.ManyToManyField(to='galeria.arte'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='idOrderItem',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='orders.orderproduct'),
        ),
    ]
