# Generated by Django 4.2.2 on 2023-06-20 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderbyclient'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderbyclient',
            name='document',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderbyclient',
            name='idOrder',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='orderbyclient',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderbyclient',
            name='quantityItems',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='orderbyclient',
            name='registerDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='orderbyclient',
            name='status',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='orderbyclient',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='orderbyclient',
            name='totalDiscount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='orderbyclient',
            name='totalItems',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='orderbyclient',
            name='totalShipping',
            field=models.IntegerField(null=True),
        ),
    ]
