# Generated by Django 4.2.1 on 2023-06-21 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_attribute_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='idQueue',
            field=models.IntegerField(null=True),
        ),
    ]
