# Generated by Django 4.2.2 on 2023-06-22 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_orderbyclient_idorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbyclient',
            name='idOrder',
            field=models.IntegerField(null=True),
        ),
    ]
