# Generated by Django 4.2.1 on 2023-06-27 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_order_products_orderproduct_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='image',
            field=models.URLField(null=True),
        ),
    ]
