# Generated by Django 4.2.1 on 2023-06-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_product_order_alter_order_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_delivery_time',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
