# Generated by Django 4.2.1 on 2023-06-22 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_customerprofile_customerexternalid'),
        ('orders', '0008_alter_product_product_delivery_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ManyToManyField(related_name='orders_customer', to='customers.customerprofile'),
        ),
    ]
