# Generated by Django 4.2.1 on 2023-06-20 23:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
