# Generated by Django 4.2.1 on 2023-07-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customerprofile_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='billingAddress',
            field=models.JSONField(null=True),
        ),
    ]
