# Generated by Django 4.2.1 on 2023-06-21 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_rename_date_of_birth_customerprofile_birthdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='customerExternalId',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
