# Generated by Django 4.2.1 on 2023-06-22 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_customerprofile_customerexternalid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
