# Generated by Django 4.2.1 on 2023-06-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_remove_order_customer'),
        ('customers', '0005_delete_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='orders',
            field=models.ManyToManyField(related_name='customers', to='orders.order'),
        ),
    ]
