# Generated by Django 4.2.2 on 2023-06-22 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='idCustomer',
            field=models.IntegerField(null=True),
        ),
    ]
