# Generated by Django 4.2.1 on 2023-06-26 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_myuser_options_alter_myuser_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'customer'), (2, 'admin'), (3, 'designer'), (4, 'reviewer'), (5, 'employee')], default=1),
            preserve_default=False,
        ),
    ]
