# Generated by Django 4.2.1 on 2023-06-28 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arte',
            name='status',
            field=models.CharField(choices=[('Envio de arte', (('AGUARDANDO', 'Aguardando'), ('ENVIADO', 'Enviado'), ('APROVADO', 'Aprovado'))), ('Confecção', (('AGUARDANDO', 'Aguardando'), ('EM_ANDAMENTO', 'Em andamento'), ('CONCLUÍDO', 'Concluído'))), ('Aprovação', (('AGUARDANDO', 'Aguardando'), ('ALTERAÇÃO', 'Alteração'), ('APROVADA', 'Aprovada')))], max_length=100),
        ),
    ]
