# Generated by Django 4.2.1 on 2023-06-28 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_orderproduct_artes'),
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arte',
            name='orderProduct',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Arte', to='orders.orderproduct'),
            preserve_default=False,
        ),
    ]
