# Generated by Django 4.2.2 on 2023-06-28 18:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_alter_arte_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='arte',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
