# Generated by Django 4.2.1 on 2023-06-29 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0004_arte_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arte',
            name='id',
        ),
        migrations.AddField(
            model_name='arte',
            name='idArte',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.RunSQL("ALTER TABLE galeria_arte DROP CONSTRAINT galeria_arte_pkey;"),
        migrations.RunSQL("ALTER TABLE galeria_arte ADD PRIMARY KEY (idArte);"),
    ]
