# Generated by Django 4.2.1 on 2023-07-04 19:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_remove_orderproduct_artes'),
        ('galeria', '0004_arte_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='arte',
            name='orderProduct',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Arte', to='orders.orderproduct'),
            preserve_default=False,
        ),
    ]
