# Generated by Django 4.2.1 on 2023-06-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0005_remove_arte_id_arte_idarte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arte',
            name='idArte',
            field=models.AutoField(default=1000, primary_key=True, serialize=False),
        ),
    ]
