# Generated by Django 4.2.2 on 2023-07-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0005_arte_orderproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='arte',
            name='rejection_reason',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
