# Generated by Django 4.2.1 on 2023-06-29 12:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0006_alter_arte_idarte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arte',
            name='idArte',
        ),
        migrations.AddField(
            model_name='arte',
            name='id',
            field=models.BigAutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
