# Generated by Django 4.2.1 on 2023-06-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0008_alter_fotografia_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('BRIEFING', 'Briefing'), ('REVISÃO', 'Revisão'), ('CONFECÇÃO', 'Confecção'), ('ALTERAÇÃO', 'Alteração'), ('APROVAÇÃO', 'Aprovação'), ('APROVADA', 'Aprovada')], default='', max_length=100),
        ),
    ]
