# Generated by Django 4.2.2 on 2023-06-23 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('galeria', '0008_alter_fotografia_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('foto', models.ImageField(blank=True, upload_to='artes/')),
                ('idCustomer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
