# Generated by Django 4.2.2 on 2023-06-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0009_artes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artes',
            name='idCustomer',
            field=models.IntegerField(null=True),
        ),
    ]
