# Generated by Django 4.2.1 on 2023-06-20 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('orders', '0003_product'),
        ('galeria', '0010_arte'),
    ]

    operations = [
        migrations.AddField(
            model_name='arte',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.customerprofile'),
        ),
        migrations.AddField(
            model_name='arte',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
    ]
